"""empty message

Revision ID: fc09c3beef0e
Revises: edd72fdc83da
Create Date: 2021-06-28 18:57:08.861721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc09c3beef0e'
down_revision = 'edd72fdc83da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('yo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'yo')
    # ### end Alembic commands ###
